# Generated by Django 3.2.25 on 2025-01-12 09:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_round', models.IntegerField(unique=True)),
                ('draw_date', models.DateTimeField()),
                ('winning_numbers', models.JSONField()),
                ('bonus_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=6)),
                ('numbers', models.JSONField()),
                ('draw_round', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('prize_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottodraw')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoticket')),
            ],
        ),
    ]
