# docker-compose.yml
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=lotto_db
      - POSTGRES_USER=lotto_user
      - POSTGRES_PASSWORD=lotto_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
